name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{c,h} | xargs clang-format -i --verbose src/geometry/main.cpp src/libgeometry/parser.cpp src/libgeometry/parser.h src/libgeometry/perimeter_and_area.cpp src/libgeometry/perimeter_and_area.h && git diff --exit-code

      - name: Build application
        run: make
